#!/usr/bin/env bash

exec 2>&1

set -e

export HOST="{{ cfg.general.host }}"
export PORT="{{ cfg.general.port }}"
export DEBUG="{{ cfg.general.debug }}"
export REQ_LOG_FORMAT="{{ cfg.general.req_log_format }}"

export AWS_REGION="{{ cfg.aws.region }}"
export AWS_STACK_ID="{{ cfg.aws.stack_id }}"
export AWS_PS_REQS_PER_SEC="{{ cfg.aws.ps_reqs_per_sec }}"
export AWS_PS_RETRY_DELAY_MS="{{ cfg.aws.ps_retry_delay_ms }}"

export HAB_GROUP"{{ cfg.hab.group }}"
export HAB_ORG="{{ cfg.hab.org }}"
export HAB_HTTP_HOST="{{ cfg.hab.http_host }}"
export HAB_HTTP_PORT="{{ cfg.hab.http_port }}"
export HAB_SUP_HOST="{{ cfg.hab.sup_host }}"
export HAB_SUP_PORT="{{ cfg.hab.sup_port }}"

export HAB_COMMAND="{{ cfg.hab.command }}"

# Assumes we've granted UNIX read permissions to this file to the user running the service
export HAB_CTL_SECRET=$(cat /hab/sup/default/CTL_SECRET)

cd {{ pkg.path }}
export SCHEMAS_DIR={{ pkg.path }}/schemas
exec node {{ pkg.path }}/dist/ita.js
