[general]
host = "localhost"
port = 3000
debug = "ita:*,ita,configtool:*,configtool"
req_log_format = ":date[iso] :method :url :status"
provider = "aws"

[aws]
region = "us-west-1"
ses_region = "us-east-1"
stack_name = ""
stack_id = ""
account_id = ""
ps_reqs_per_sec = 3
ps_retry_delay_ms = 5000
server_domain = ""

[hab]
org = ""
group = "default"
http_host = "127.0.0.1"
http_port = 9631
sup_host = "127.0.0.1"
sup_port = 9632
command = "hab"
