general.reticulum_server = { "type" = "string" }
general.cors_proxy_server = { "type" = "string" }
general.base_assets_path = { "type" = "string", default = "/" }
general.thumbnail_server = { "type" = "string" }
general.non_cors_proxy_domains = { "type" = "string" }
general.postgrest_server = { "type" = "string" }
general.sentry_dsn = { "type" = "string", "default" = "" }
general.ga_tracking_id = { "type" = "string", "default" = "" }
deploy.type = { "type" = "string", "default" = "none" }
deploy.region = { "type" = "string", "default" = "" }
deploy.target = { "type" = "string", "default" = "" }
