general.host = { "type" = "string", "default" = "localhost" }
general.port = { "type" = "number", "default" = 3000 }
general.debug = { "type" = "string", "default" = "ita*,configtool*" }
general.req_log_format = { "type" = "string", "default" = ":date[iso] :method :url :status" }
aws.region = { "type" = "string", "default" = "us-west-1" }
aws.stack_id = { "type" = "string", "default" = "" }
aws.ps_reqs_per_sec = { "type" = "number", "default" = 3 }
aws.ps_retry_delay_ms = { "type" = "number", "default" = 5000 }
hab.group = { "type" = "string", "default" = "default" }
hab.http_host = { "type" = "string", "default" = "localhost" }
hab.http_port = { "type" = "number", "default" = 9631 }
hab.sup_host = { "type" = "string", "default" = "localhost" }
hab.sup_port = { "type" = "number", "default" = 9632 }
db.username = { "type" = "string", "default" = "admin" }
db.password = { "type" = "string", "default" = "admin" }
db.hostname = { "type" = "string", "default" = "localhost" }
db.database = { "type" = "string", "default" = "ret_dev" }
