deploy.type = { "type" = "string" }
deploy.assets_target = { "type" = "string" }
deploy.assets_region = { "type" = "string" }
deploy.redirector_target = { "type" = "string" }
deploy.redirector_region = { "type" = "string" }
