db.uri = { "type" = "string" }
db.schema = { "type" = "string", "default" = "ret0_admin" }
db.anon_role = { "type" = "string", "default" = "postgrest_anonymous" }
db.pool = { "type" = "number", "default" = 10 }
server.host = { "type" = "string", "default" = "127.0.0.1" }
server.port = { "type" = "number", "default" = 3000 }
security.jwt_secret_enabled = { "type" = "boolean", "default" = true }
security.jwt_aud = { "type" = "string", "default" = "ret_perms" }
security.role_claim_key = { "type" = "string", "default" = ".postgrest_role" }
